# Generated by Django 2.2 on 2020-12-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('blog', models.TextField()),
                ('starttime', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('publishtime', models.DateTimeField(null=True)),
            ],
        ),
    ]
